
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: airflow
      MYSQL_PASSWORD: ayushlakra
      MYSQL_DATABASE: airflow
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

  airflow-webserver:
    image: apache/airflow:2.9.0
    container_name: airflow_web
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqldb://airflow:ayushlakra@mysql:3306/airflow
      AIRFLOW__CORE__FERNET_KEY: 'YsFvW3HOJ8QgOoCA1uCmP6w4_AcL7vxJ3T1q4lg3IAU='
      AIRFLOW__WEBSERVER__SECRET_KEY: 'something_secret'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8081:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.0
    container_name: airflow_scheduler
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqldb://airflow:ayushlakra@mysql:3306/airflow
      AIRFLOW__CORE__FERNET_KEY: 'YsFvW3HOJ8QgOoCA1uCmP6w4_AcL7vxJ3T1q4lg3IAU='
      AIRFLOW__WEBSERVER__SECRET_KEY: 'something_secret'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
    command: scheduler

volumes:
  mysql_data:
